### ISSUE TITLE
For signal.saturation Tercen is different to Bio navigator - should get same result

### ISSUE THREAD

**Issue by martin1english** [tercen/pamsoft_grid_qt_operator#1]
For signal_saturation quantitation type.

Tercen image analysis gives a different result to Bionavigator

Link to workflow
https://stage.tercen.com/pamgene/w/271aeb08affeb9a45f8390adc620ffdb

**Comment by tsmonteiro** [comment]
Fixed. There was a difference in the signal saturation parameter.
