### ISSUE TITLE
which qt's to keep?

### ISSUE THREAD

**Issue by rdewijn** [tercen/pamsoft_grid_qt_operator#2]
@amaurel 
@martin1english

Propose to have a standard version and a separate operator called e.g. PamSoft_grid_qtdiagnostics_operator.

In the list below a qt has a score 0,1, or 2:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\rdwijn\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\rdwijn\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

score | means
-- | --
0 | remove
1 | diagnostics only
2 | keep

</body>

</html>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link id=Main-File rel=Main-File
href="file:///C:\Users\rdwijn\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\rdwijn\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

ds4.Rse_Background | 0
-- | --
ds4.Rse_MedianSigmBg | 0
ds4.Rse_Signal | 0
ds4.Std_Background | 0
ds4.Std_Signal | 0
ds4.Sum_Background | 0
ds4.Sum_Signal | 0
ds4.Bad_Spot | 1
ds4.Diameter | 1
ds4.Empty_Spot | 1
ds4.Fraction_Ignored | 1
ds4.Position_Offset | 1
ds4.Replaced_Spot | 1
ds4.grdImageNameUsed | 1
ds4.Mean_Background | 1
ds4.Mean_SigmBg | 1
ds4.Mean_Signal | 1
ds4.Median_Background | 2
ds4.Median_SigmBg | 2
ds4.Median_Signal | 2
ds4.Signal_Saturation | 2
ds4.X_Position | 1
ds4.Y_Position | 1

</body>

</html>

**Comment by tsmonteiro** [comment]
Added the option to output diagnostic columns or not.
